name: 1.0$(Rev:.r).99  # NOTE: the Rev part includes a dot, so dont add it yourself. Can also use date formatting if desired $(Date:yyyyMMdd)
# more info ^^ https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=yaml

pool:
  vmImage: 'ubuntu-16.04'

trigger:
  - master

steps:
  - script: echo '$(BuildNumber)' # outputs customized build number from NAME variable above

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)/Templates'
    inputs:
      SourceFolder: deployment
      Contents: '*.json'
      TargetFolder: '$(build.artifactstagingdirectory)/Templates'

  - task: Npm@1
    displayName: 'npm custom'
    inputs:
      command: custom
      verbose: false
      customCommand: 'install --production'

  - task: ArchiveFiles@2
    displayName: 'Archive $(Build.SourcesDirectory)'
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: false

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
  
  